### ISSUE TITLE
Alexa Skill Intents for API (Call Graph)

### ISSUE THREAD

**Issue by aditya2592** [thebayesianconspiracy/gringotts#3]
Diagram started here - https://www.draw.io/#G0B_X4iY6vWx2JRHI4ZXFhZENycGM

**Comment by aditya2592** [comment]
Version 1 of VUI design is done, things added : 

- Checking balance
- Recent transactions
- Add Payee
- Billl payment

In next version, users responses to Alexa questions may be required to be mapped to new intent types

![voice pay vui 1](https://cloud.githubusercontent.com/assets/2186078/24626746/ec563f8e-18cf-11e7-9bcc-6b8ca94f0426.png)

**Comment by sam17** [comment]
We should list down necessary intents also as part of this issue.

**Comment by aditya2592** [comment]
I could think of following : 

- BalanceIntent
- RecentTransactionsIntent
- AddPayeeIntent
- TransferMoneyIntent
- AddVPAIntent

First 2 are added in the skill and in request handler in recent_transactions_branch

**Comment by sam17** [comment]
We need to divide into sessions first instead of intent and each sessions can consist of multiple intents. Some intents can be in multiple sessions too:
- Balance Session
  - Auth Intent
  - Balance Intent 
- Transactions Session
  - Auth Intent
  - RangePresentIntent
- Transfer Session
  - AuthIntent
  - TransferIntent
  - AskPayeeIntent
  - AskAmountIntent
  - ConfirmationIntent
- Add Payee Session
  - AuthIntent
  - AskPayeeNameIntent
  - AskPayeeDetailsIntent
  - ConfirmationIntent
- Check Bill Session
  - AuthIntent
  - AskBillNameIntent
  - ConfirmationIntent
- Register Biller Session
  - AuthIntent
  - AskBillerNameIntent
  - AskBillerDetailsIntent
  - ConfirmationIntent
- Pay Bill Session
  - AuthIntent
  - AskBillNameIntent
  - AskAmountIntent
  - ConfirmationIntent

**Comment by sam17** [comment]
The AuthIntent may or may not be triggered depending on if auth token is expired or not.

**Comment by sam17** [comment]
I guess now this issue can be closed. @aditya2592

**Comment by sam17** [comment]
- Credit Card Details
  - AuthIntent
  - AskCreditCardDetails Intent
  - AskCVV Intent
  - Confirmation Intent

**Comment by aditya2592** [comment]
Credit Card Session

- Check Bill
- Pay Bill
